pipeline {
    agent any

    stages {
        stage('build') {
            steps {
                bat "apps/jenkins/build.bat"
            }
        }
        stage('unit_test') {
            steps {
                bat "apps/jenkins/unit_test.bat"
            }
        }
        stage('deploy') {
            steps {
                bat "apps/jenkins/deploy.bat"
            }
        }
    }
}