---

# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: FALSE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: FALSE
  :test_file_prefix: test_

:environment:
  - :path:
    - 'C:\Program Files\IAR Systems\Embedded Workbench 9.0\arm\bin'
    - 'C:\Program Files\IAR Systems\Embedded Workbench 9.0\common\bin'
    - #{ENV['PATH']}
  - :executable:
    - 'C:\Program Files\IAR Systems\Embedded Workbench 9.0\common\bin\iarbuild.exe'

:paths:
  :test:
    - +:test/test_method/**
    - +:test/test_common/**
    - -:test/support
  :source:
    - src/**
    - ../sdk/**
  :support:
    - test/support
  :libraries: []

:defines:
  :common: &common_defines []
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :cexception_include:
  :treat_inlines:
    :include
  :inline_function_patterns: ['static inline __attribute__ \(\(always_inline\)\)']
  :plugins:
    - :ignore_stateless
    - :callback
    - :array
    - :ignore_arg
    - :expect_any_args
    - :return_thru_ptr
  :treat_as:
    uint8_t:    HEX8
    uint16_t:   HEX16
    uint32_t:   UINT32
    int8_t:     INT8
    int16_t:    INT16
    int32_t:    INT
    bool:       UINT8

:tools:
  :test_compiler:
    :executable: iccarm
    :name: 'IAR test compiler'
    :arguments:
      - -D APP_TIMER_V2
      - -D APP_TIMER_V2_RTC1_ENABLED
      - -D BOARD_PCA10040
      - -D CONFIG_GPIO_AS_PINRESET
      - -D FLOAT_ABI_HARD
      - -D NRF52
      - -D NRF52832_XXAA
      - -D NRF52_PAN_74
      - -D NRF_SD_BLE_API_VERSION=7
      - -D S132
      - --debug
      - --endian=little 
      - --cpu=Cortex-M4 
      - -e
      - --fpu=VFPv4_SP 
      - -Ohz
      - --preprocess "build/test/list"
      - --dlib_config "C:\Program Files\IAR Systems\Embedded Workbench 9.0\arm\inc\c\DLib_Config_Normal.h"
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -D"$": COLLECTION_DEFINES_TEST_AND_VENDOR
      - -o "${2}"
      - --diag_suppress=Pa050
      - '"${1}"'

  :test_linker:
    :executable: ilinkarm
    :name: 'IAR test linker'
    :arguments:
      - --vfe
      - --inline
      - --redirect _Printf=_PrintfFull
      - --redirect _Scanf=_ScanfFull
      - --semihosting
      - --config "C:\Program Files\IAR Systems\Embedded Workbench 9.0\arm\config\generic_cortex.icf"
      - --map "ide\pca10040\s132\iar\_build\ble_app_uart_pca10040_s132.map"
      - -o "${2}"
      - '"${1}"'

  :test_fixture:
    :executable: cspybat
    :name: 'CSpyBat test runner'
    :arguments:
      - '"C:\Program Files\IAR Systems\Embedded Workbench 9.0\arm\bin\armproc.dll"'
      - '"C:\Program Files\IAR Systems\Embedded Workbench 9.0\arm\bin\armsim2.dll"'
      - '"${1}"'
      - --plugin "C:\Program Files\IAR Systems\Embedded Workbench 9.0\arm\bin\armbat.dll"
      - --backend -B
      - --endian=little
      - --cpu=Cortex-M4
      - --fpu=VFPv4_sp
      - --semihosting

# LIBRARIES
# These libraries are automatically injected into the build process. Those specified as
# common will be used in all types of builds. Otherwise, libraries can be injected in just
# tests or releases. These options are MERGED with the options in supplemental yaml files.
:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: []    # for example, you might list 'm' to grab the math library
  :test: []
  :release: []

:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator

...
